"""Behaviour spec for the tiny stats package.

Exactly two tests fail against the seeded ``stats.py``: ``test_median_odd_length`` (the off-by-one)
and ``test_variance_is_non_negative`` (the sign flip). The rest pass. Do not edit this file to make
the suite green — fix ``stats.py``.
"""

import stats


def test_mean_of_a_simple_sequence():
    assert stats.mean([1, 2, 3, 4]) == 2.5


def test_mean_of_a_single_value():
    assert stats.mean([7]) == 7


def test_median_even_length():
    assert stats.median([1, 2, 3, 4]) == 2.5


def test_median_odd_length():
    # The true middle of a sorted 5-element list is the third element.
    assert stats.median([5, 3, 1, 2, 4]) == 3


def test_variance_is_non_negative():
    # Population variance of [1, 2, 3, 4, 5] is 2.0 — never negative.
    assert stats.variance([1, 2, 3, 4, 5]) == 2.0


def test_variance_of_identical_values_is_zero():
    assert stats.variance([4, 4, 4]) == 0.0
